[build]
builder = "dockerfile"
dockerfilePath = "./MyWebSite.Server/Dockerfile"

[deploy]
startCommand = "dotnet /app/MyWebSite.Server"
restartPolicyType = "always"
healthcheckPath = "/health"
