[build]
builder = "dockerfile"
dockerfilePath = "./MyWebSite.Server/Dockerfile"

[deploy]
startCommand = "-lah app/Resources/Images && dotnet /app/MyWebSite.Server.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
